name: Deploy Portfolio

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/portfolio:latest

      - name: Notify n8n workflow
        if: success()
        run: |
          curl -X POST https://n8n.yourdomain.com/webhook/deploy \
            -H "Content-Type: application/json" \
            -d '{"status": "success", "app": "portfolio"}'
